server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: 1111111111
  jpa:
    hibernate:
      ddl-auto: update
